### ISSUE TITLE
Comcast\PhpLegalLicenses\Console\string, string given

### ISSUE THREAD

**Issue by BWhitten** [Comcast/php-legal-licenses#1]
The following error
`Error Output: PHP Catchable fatal error:  Argument 1 passed to Comcast\PhpLegalLicenses\Console\GenerateCommand::generateDependencyText() must be an instance of Comcast\PhpLegalLicenses\Console\string, string given`

Is given when running, this is due to the type hint 'string' in the function definitions of these two functions, PHP doesn't require hints for primative types.

This is using PHP 5.6, prior to 7 only hinting for objects and arrays is used.

**Comment by orediggerco** [comment]
Sorry about that Ben. Should be fixed now!
