### ISSUE TITLE
Support PHP 8.0.0

### ISSUE THREAD

**Issue by jonathan-shahen** [Comcast/php-legal-licenses#18]
**Is your feature request related to a problem? Please describe.**
I am unable to use your software with PHP 8

**Describe the solution you'd like**
Update `composer.json` to allow `^8.0`

```
$ composer update
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - comcast/php-legal-licenses[v1.1.0, ..., v1.1.2] require php ^5.6 || ^7.0 || ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - comcast/php-legal-licenses[v1.1.3, ..., v1.1.4] require php ^5.6 || ^7.1 || ^7.2 || ^7.3 || ^7.4 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires comcast/php-legal-licenses ^1.1 -> satisfiable by comcast/php-legal-licenses[v1.1.0, ..., v1.1.4].
```

**Comment by judge2020** [comment]
Yep - this is the last dependency my project depends on that doesn't indicate PHP 8 compatibility. Installing with `--ignore-platform-reqs` then `vendor/bin/php-legal-licenses generate` seems to work in my repo on PHP 8.

**Comment by orediggerco** [comment]
Thanks for submitting this, I'll get it updated soon!

**Comment by jonathan-shahen** [comment]
@orediggerco I submitted a PR

**Comment by orediggerco** [comment]
PHP Version constraints are now removed as of v1.1.5.
