### ISSUE TITLE
[BUG] Requirements prevent installation with Symfony 6.0 dependencies present

### ISSUE THREAD

**Issue by milkboy** [Comcast/php-legal-licenses#20]
**Describe the bug**
This package is not installable when using Symfony 6 due to package.json version constraints.

**To Reproduce**
1. `composer require symfony/console=6.0`
2. `composer require Comcast/php-legal-licenses`
3. See error: 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - comcast/php-legal-licenses[v1.1.0, ..., v1.1.2] require php ^5.6 || ^7.0 || ^7.1 -> your php version (8.0.12) does not satisfy that requirement.
    - comcast/php-legal-licenses[v1.1.3, ..., v1.1.4] require php ^5.6 || ^7.1 || ^7.2 || ^7.3 || ^7.4 -> your php version (8.0.12) does not satisfy that requirement.
    - comcast/php-legal-licenses[v1.1.5, ..., v1.1.6] require symfony/console ~2.3|~3.0|~4.0|~5.0 -> found symfony/console[v2.3.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3] but it conflicts with your root composer.json require (6.0).
    - Root composer.json requires comcast/php-legal-licenses ^1.1 -> satisfiable by comcast/php-legal-licenses[v1.1.0, ..., v1.1.6].
```

**Expected behavior**
Installation success.

**Run Environment (please complete the following information):**
OS, PHP version, composer version etc are not applicable

**Additional context**
Tried to create a PR, the the only response is
![image](https://user-images.githubusercontent.com/1941814/154487688-19b497b8-7560-4f18-b5af-4eb56553fb08.png)

**Comment by orediggerco** [comment]
Thanks for the report @milkboy, I'll look into this today. 

It's strange that you couldn't open a PR yourself. Did you get a prompt to sign the CLA?

**Comment by milkboy** [comment]
just the error message in the pic. I assumed there would be a prompt to sign something, but "some validation" failed.. Anyhow, should not be a huge effort to change the dependency version constraints, as everything seems to work just fine with Symfony 6 also :smile:

**Comment by orediggerco** [comment]
v1.2.0 released, thanks for the report!
